### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by jacosro** [mistupv/JavaSDGSlicer#34]
Static attributes of each class are represented as global variables. This means that each method declaration will have a `global_formal_in` and `global_formal_out` parameter for each one of the global variables of the program (static attributes of every class). Consequently, every method call will also have `global_actual_in` and `global_actual_out` nodes for each global variable.

Four new `NodeType`s must be added: `GLOBAL_FORMAL_IN`, `GLOBAL_FORMAL_OUT`, `GLOBAL_ACTUAL_IN`, `GLOBAL_ACTUAL_OUT`, in order to be able to distinguish them from normal parameters.

@cargaji What do you think?

**Comment by cargaji** [comment]
This issue can be split into static fields (see #46) and class fields (already supported in 1.3.0).
